network:
  version: 2
  renderer: NetworkManager

  ethernets:
    # Interface d'administration (DHCP)
    enp1s0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false

    # ----------------------------------------------------
    # CHEMINS MPTCP (Côté client: 10.0.X.10)
    # ----------------------------------------------------

    eth0:
      addresses: [10.0.1.10/24]
      dhcp4: false
      routes: []

    eth1:
      addresses: [10.0.2.10/24]
      dhcp4: false
      routes: []

    eth2:
      addresses: [10.0.3.10/24]
      dhcp4: false
      routes: []

    eth3:
      addresses: [10.0.4.10/24]
      dhcp4: false
      routes: []
