network:
  version: 2
  renderer: networkd

  ethernets:
    enp1s0:
      dhcp4: true
      routes:
        - to: 0.0.0.0/0
          via: 192.168.122.1
          metric: 1000

    enp7s0:
      dhcp4: false
      addresses: [10.0.1.10/24]

    enp8s0:
      dhcp4: false
      addresses: [10.0.2.10/24]

    enp9s0:
      dhcp4: false
      addresses: [10.0.3.10/24]

    enp10s0:
      dhcp4: false
      addresses: [10.0.4.10/24]
