network:
  version: 2
  renderer: NetworkManager

  ethernets:
    # Interface d'administration
    enp7s0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false

    # ----------------------------------------------------
    # CHEMINS MPTCP (Côté serveur: 192.168.X.10)
    # ----------------------------------------------------

    enp7s0:
      addresses: [192.168.1.10/24]
      dhcp4: false
      routes: []

    enp8s0:
      addresses: [192.168.2.10/24]
      dhcp4: false
      routes: []

    enp9s0:
      addresses: [192.168.3.10/24]
      dhcp4: false
      routes: []

    enp10s0:
      addresses: [192.168.4.10/24]
      dhcp4: false
      routes: []
